Team-WSS/WSS-iOS

- WSSiOS/WSSiOS.xcodeproj/project.pbxproj
- WSSiOS/WSSiOS/App/SceneDelegate.swift
- WSSiOS/WSSiOS/Source/Presentation/Base/WSSMainButton.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageView.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/ViewController.swift
#21 
<br/>
공통으로 사용하는 메인버튼을 구현하였습니다
<br/>
<br/>
didMoveToSuperview() 라는 함수를 처음 알게되었습니다.
superView 가 로드되면 실행되는 함수랍니당!
```swift
override func didMoveToSuperview() {
super.didMoveToSuperview()
if superview != nil {
setLayout()
}
}
```
<br/>
bottom 을 $0.bottom.equalTo(super.safeAreaLayout) 으로 주었더니 실행되지 않았습니다 ㅠㅠ (위에 올라가 있더라구요)
그 이유는 아직 super 가 결정되지 않아 super 를 UIButton 으로 판단해버려 UIButton의 safeAreaLayout 을 잡아버리는데! 버튼은 safeAreaLayout 이 없기 때문에 버튼이 포함된 뷰를 생성하여~~ 이런식으로 된다고 합니다 ㅠㅠ 그래서 아래처럼 구현해 주었습니다!
```swift
private func setLayout() {
self.snp.makeConstraints() {
$0.centerX.equalToSuperview()
$0.leading.equalToSuperview().inset(20)
$0.bottom.equalToSuperview().inset(34)
$0.height.equalTo(53)
}
}
```
<br/>
<br/>
아래처럼 사용하시면 됩니다! 레이아웃도 자동으로 잡아주니까요, 편하게 사용하세용!
```swift
private var mainButton = …
```
> [Feat] #21 - 공통 메인버튼 구현

- WSSiOS/WSSiOS.xcodeproj/project.pbxproj
- WSSiOS/WSSiOS/App/SceneDelegate.swift
- WSSiOS/WSSiOS/Resource/Assets.xcassets/exampleAvater.imageset/Contents.json
- WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageChangeNicknameView.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageChangeNicknameViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageViewController.swift
#27 
<br/>
닉네임을 수정하는 뷰를 구현하였습니다.
<br/>
<br/>
Rx가 어색해서 레퍼런스 많이 참고해서 구현하였는데, 분기처리나 로직 등등 더 간단하게 코드 구현할 수 있는 부분이 있다면 말씀 주시면 감사하겠습니다!
```swift
private func textFieldEvent() {
rootView.changeNicknameTextField.rx.controlEvent([.editingDidBegin, .editingChanged])
.asObservable()
.subscribe(onNext: { _ in
self.rootView.textFieldUnderBarView.backgroundColor = .Primary100
})
.disposed(by: disposeBag)
rootView.changeNicknameTextField.rx.controlEvent([.editingDidEnd])
.asObservable()
.subscribe(onNext: { _ in
self.rootView.textFieldUnderBarView.backgroundColor = .Gray200
})
.disposed(by: disposeBag)
rootView.changeNicknameTextField.rx.text
.subscribe(onNext: { text in
if let countText = text?.count {
self.rootView.countNicknameLabel.text = "\(countText)/10"
}
})
.disposed(by: disposeBag) …
```
> [Feat] #27 - MyPageChangeNicknameView UI 및 기능 구현

- WSSiOS/WSSiOS.xcodeproj/project.pbxproj
- WSSiOS/WSSiOS/App/SceneDelegate.swift
- WSSiOS/WSSiOS/Source/Presentation/Base/WSSMainButton.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageAssistantView/MyPageModalAvatarFeatureLabelView.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageCell/MyPageInventoryCollectionViewCell.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageCustomModalView.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageCustomModalViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageViewController.swift
#27 
<br/>
모달을 구현하였습니당
<br/>
<br/>
캐릭터 특성 라벨은 PPP 때 쓰던걸로 만들었습니당
```swift
stackView.addArrangedSubviews(emptylabel1,
modalAvaterBadgeImageView,
modalAvaterTitleLabel,
emptylabel2)
```
<br/>
++위처럼 잡아주던걸 StackView 자체적으로 만들어주어 편하게 emptyView 사용 안해도 되도록 하였습니다 :)
```swift
stackView.snp.makeConstraints() {
$0.horizontalEdges.equalToSuperview().inset(20)
$0.verticalEdges.equalToSuperview().inset(11)
}
```
<br/>
<br/>
시뮬레이션에서 버벅이는데 제 시뮬에서는 잘 돌아갑니다!
PageVC 에서 modalVC 가 뜰 때는 뒤에 반투명한 배경이 뜨고 모달이 뜨는데,
반대로 modalVC 를 dismiss 할 때 PageVC의 반투명한 배경이 사라지지 않았습니다.
이 에러는 네트워크 붙이면서 한 번 더 구현해보겠습니당
공통 컴포넌트로 사용하는 WSSMainButton 의 bottom 값을 해제했습니다.
아무래도 항상 그 래이아웃으로 잡히는 게 아니라서 불편하더라구요용
참고해두세요!
```swift
if superview != nil {
self.snp.makeConstraints() {
$0.centerX.equalToSuperview() …
```
> [Design] #27 - ModalView UI 및 기능 구현

- WSSiOS/WSSiOS.xcodeproj/project.pbxproj
- WSSiOS/WSSiOS/Resource/Assets.xcassets/icAlert/icAlertCheck.imageset/Contents.json
- WSSiOS/WSSiOS/Resource/Assets.xcassets/icAlert/icAlertCheck.imageset/Group 1171275377.svg
- WSSiOS/WSSiOS/Resource/Constants/Images/ImageLiterals.swift
- WSSiOS/WSSiOS/Resource/Extensions/UIViewController+.swift
- WSSiOS/WSSiOS/Source/Data/DTO/NovelMemoResult.swift
- WSSiOS/WSSiOS/Source/Presentation/Base/WSSToastView.swift
- WSSiOS/WSSiOS/Source/Presentation/Memo/MemoViewController/MemoEditViewController.swift
#21 
<br/>
공통 토스트 구현했습니다. 
<br/>
- 토스트 케이스 enum으로 정의했습니다.
- 토스트를 띄우는 메서드를 UIViewController+ 에 정의했습니다.
- 토스트를 띄우고 싶은 시점에서 아래 메서드를 호출하면 됩니다.
```swift
showToast(.memoDelete)
```
<br/>
<br/>
<br/>
<br/>
> [Feat] #21 - 공통 토스트 구현

- WSSiOS/WSSiOS/Source/Presentation/Library/LibraryViewController/LibraryViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/Memo/MemoViewController/MemoEditViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailView.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailViewController/NovelDetailViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalViewController/RegisterNormalViewController.swift
#85
<br/>
메모뷰 1차 QA 반영완료
<br/>
- 공백 입력시 메모 등록 버튼 비활성화 했습니다.
- 검색뷰에서 이미 등록한 작품 클릭해 수정 시, 서재뷰로 이동 후 해당 작품 디테일 뷰 push 하도록 구현했습니다.
- 작품 디테일 뷰에서 작품 정보 수정 시, pop 하도록 구현했습니다.
- 작품 정보 수정 시 정보 탭을 띄우도록 수정했습니다.
<br/>
<br/>
- 뷰 이동 코드가 막 매끄럽진 않은데유,, 나중에 수정합시당
<br/>
<br/>
> [Fix] #85 - 메모/정보 뷰 1차 QA 반영

- WSSiOS/WSSiOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- WSSiOS/WSSiOS/Source/Presentation/Search/SearchView/SearchAssistantView/SearchHeaderView.swift
- WSSiOS/WSSiOS/Source/Presentation/Search/SearchViewController/SearchViewController.swift
closed #91 
<br/>
- SearchView 1차 QA 반영하여 수정했습니다. 
<br/>
- 검색뷰로 넘어가면 키보드가 바로 올라오고 키보드 내 search버튼 클릭 시 키보드 내려갑니다.
- searchbar 내 placeholder 삭제했습니다. 
<br/>
<br/>
- 무한스크롤은 RecordView, SearchView 한꺼번에 이슈 만들어서 구현진행해보겠습니당 ~
<br/>
<br/>
> [Fix] #91 - SearchView 1차 QA 반영

- WSSiOS/WSSiOS/Source/Presentation/Library/LibraryViewController/LibraryBaseViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/Library/LibraryViewController/LibraryViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/Record/RecordViewController/RecordViewController.swift
#99 
<br/>
명진과 가볍게 진행한 1.5차 QA 결과 반영
<br/>
- 기록 뷰에서 메모 read 뷰에 갔다가 메모 삭제하면 삭제 토스트가 안 뜸
- 등록 뷰에서 상단 네비게이션 바 구분선이 사라지지 않는 문제 해결
<br/>
<br/>
<br/>
<br/>
> [Fix] #99 - 1.5차 QA 결과 반영

- WSSiOS/WSSiOS.xcodeproj/project.pbxproj
- WSSiOS/WSSiOS/Resource/Extensions/UIViewController+.swift
- WSSiOS/WSSiOS/Source/Presentation/DeletePopup/DeletePopupViewController/DeletePopupViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/DeletePopup/DeletePopupViewModel/DeletePopupViewModel.swift
#125
<br/>
DeletePopupViewController에 MVVM 패턴을 적용했습니다.
<br/>
- NovelDetailViewModel을 추가해 기존 비즈니스 로직을 ViewModel로 이동시켰습니다.
- PopupStatus를 Input으로 받아 케이스를 나눠 deleteButtonDidTapEvent를 subscribe 해주었습니다.
<br/>
없어용가리
<br/>
popupStatus도 viewModel이 들고 있는게 맞다는 생각이 들지만,, 뷰컨에서 rootView 초기화시 popupStatus가 필요해 일단 뷰컨에서 들고 있도록 구현했쌉다 🤓
<br/>
> [Refactor] #125 - DeletePopup MVVM 패턴 적용

- WSSiOS/WSSiOS/Resource/Assets.xcassets/Color/WSSGray70.colorset/Contents.json
- WSSiOS/WSSiOS/Resource/Extensions/UILabel+.swift
- WSSiOS/WSSiOS/Source/Presentation/Feed/FeedView/FeedAssistantView/FeedDetailContentView.swift
- WSSiOS/WSSiOS/Source/Presentation/Feed/FeedViewController/FeedGenreViewController.swift
close #151 
<br/>
- 안녕하세요.. 바꾼 Line Height Multiple로 작업하다보니 한줄 짜리 라벨에도 위쪽에만 행간만큼 Inset이 생기는 등 몇가지 문제가 있더라구요..? 그래서 사람들은 도대체 어떻게 하나 하고 찾아봤습니다.
<br/>
- 그 결과 피그마 상의 line Height(percentage)에 맞게 lineHeight를 잡고 거기에 baseLineOffset을 줘서 글씨를 가운데 정렬로 바꿔주는 형태로 하더라구요.. 이렇게 하니까 피그마 상의 글씨영역 inset까지 다 동일하게 잘 맞더라구요!!?
- lineHeight를 고정 값으로 주는 거긴 하지만, 폰트가 바뀌는 일도 없기도 하고 피그마 상의 라벨과 동일하게 할 수 있는 최선의 방법이라 생각합니다.
- 폰트 크기 값을 받아서 baseLineOffset을 고정으로 줘야 하는거라 lineHeightMultiple을 그대로 쓸 수 없어서, LineHeight로 변경했어요
<br/>
이렇게 글씨가 예쁘게 중앙정렬 된 모습을 확인 할 수 있어요. 
- lineHeightMultiple만 하면 글씨가 Label 영역의 아래쪽에 붙어있게 되구요, 
- LineSpacing만 주는 경우는 두 줄 간의 간격만 설정하는 거라 한줄일 때 Label 영역이 피그마와 다르게 글씨에 딱 붙어서 잡히고, 위아래 여백이 없더라구요..
<br/>
- 아주 간단한 변경사항입니다!! 
<br/>
> [Chore] #151 - Line Height 피그마 상의 디자인과 동일하게 작동하도록 수정

- WSSiOS/WSSiOS/App/SceneDelegate.swift
- WSSiOS/WSSiOS/Network/Foundation/APIConstants.swift
- WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
- WSSiOS/WSSiOS/Resource/Extensions/UIViewController+.swift
- WSSiOS/WSSiOS/Source/Presentation/Base/WSSTabBarController.swift
- WSSiOS/WSSiOS/Source/Presentation/Base/WSSTabBarItem.swift
- WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeView/HomeAssistantView/HomeInduceLoginModalView.swift
- WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeView/HomeAssistantView/HomeInterestView.swift
- WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeView/HomeAssistantView/HomeTasteRecommendView.swift
- WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeView/HomeAssistantView/HomeUnregisterView.swift
- WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeView/HomeView.swift
- WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeViewController/HomeViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeViewModel/HomeViewModel.swift
close #265 
<br/>
- 비로그인일 때 홈뷰 UI 분기처리 완료했습니다.
<br/>
- `APIConstants`에서 로그인 여부를 Boolean변수로 넘겨주면 `SceneDelegate`에서 분기처리 할 수 있도록 구현했습니다. 
<br/>
- 로그인 했을 때 (카카오, 네이버, 애플 버튼 클릭 하면 다 이동합니다.)
https://github.com/user-attachments/assets/f787e2a0-bd18-4ace-888f-bf55a2223759
- 비로그인 상태일 때 
https://github.com/user-attachments/assets/b6036169-bc5a-4fbf-9c00-0d5809bfe179
<br/>
<br/>
<br/>
> [Feat] #265 - 로그인 여부에 따른 홈뷰 UI 분기처리 구현

- WSSiOS/WSSiOS/Source/Presentation/Search/NormalSearch/NormalSearchView/NormalAssistantView/NormalSearchHeaderView.swift
- WSSiOS/WSSiOS/Source/Presentation/Search/NormalSearch/NormalSearchViewController/NormalSearchViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/Search/NormalSearch/NormalSearchViewModel/NormalSearchViewModel.swift
close #297 
<br/>
- NormalSearch 내 TextField UI 수정했습니다.
- Cell 클릭 시 해당 Cell에 대한 작품상세뷰로 이동하도록 반영했습니다. 
<br/>
기존엔 editing 에 따른 UI 변화가 없었습니다. 
효원이가 구현해 둔 textField UI 및 update함수 반영했습니다 👍
<br/>
https://github.com/user-attachments/assets/8124eb3b-142b-40a2-9b91-0298724c0068
<br/>
- 없습니다
<br/>
- 없습니다
<br/>
> [Fix] #297 - NormalSearch UI 수정 및 Cell 클릭 시 작품상세뷰로 이동

- WSSiOS/WSSiOS.xcodeproj/project.pbxproj
- WSSiOS/WSSiOS/Network/Auth/AuthService.swift
- WSSiOS/WSSiOS/Resource/Constants/URLs/URLs.swift
- WSSiOS/WSSiOS/Resource/Helper/ModuleFactory.swift
- WSSiOS/WSSiOS/Source/Data/DTO/AuthResult.swift
- WSSiOS/WSSiOS/Source/Data/Repository/AuthRepository.swift
- WSSiOS/WSSiOS/Source/Presentation/Login/LoginViewModel/LoginViewModel.swift
- WSSiOS/WSSiOS/WSSiOS.entitlements
close #305 
<br/>
애플로그인 구현했습니다.
<br/>
**1. 애플로그인 버튼 클릭 시 `ASAuthorizationAppleIDProvider` request 생성**
https://github.com/Team-WSS/WSS-iOS/blob/5fb8430367e0a830425491728013eed679c41011/WSSiOS/WSSiOS/Source/Presentation/Login/LoginViewModel/LoginViewModel.swift#L162-L169
**2. `ASAuthorizationControllerDelegate` 상속, 계정 정보 요청 후 성공 시 API 호출**
https://github.com/Team-WSS/WSS-iOS/blob/5fb8430367e0a830425491728013eed679c41011/WSSiOS/WSSiOS/Source/Presentation/Login/LoginViewModel/LoginViewModel.swift#L179-L195
**3. `loginWithApple` API 호출**
- UserDefaults 에 accessToken, refreshToken 저장
- `UserDefaults.standard.string(forKey: "ACCESS_TOKEN")` - accessToken 접근
- `UserDefaults.standard.string(forKey: "REFRESH_TOKEN")` - refreshToken 접근
- `isRegister` true인 경우 -> home으로 이동, false인 경우 -> onboarding으로 …
> [Feat] #305 - 애플로그인 구현

- WSSiOS/WSSiOS.xcodeproj/project.pbxproj
- WSSiOS/WSSiOS/App/SceneDelegate.swift
- WSSiOS/WSSiOS/Info.plist
- WSSiOS/WSSiOS/Resource/Extensions/UIViewController+.swift
- WSSiOS/WSSiOS/Source/Data/Repository/RecommendRepository.swift
- WSSiOS/WSSiOS/Source/Presentation/Base/InduceLogin/InduceLoginView.swift
- WSSiOS/WSSiOS/Source/Presentation/Base/InduceLogin/InduceLoginViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/Base/WSSTabBarController.swift
- WSSiOS/WSSiOS/Source/Presentation/Base/WSSTabBarItem.swift
- WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeView/HomeAssistantView/HomeInterestView.swift
- WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeView/HomeAssistantView/HomeTasteRecommendView.swift
- WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeView/HomeView.swift
- WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeViewController/HomeViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeViewModel/HomeViewModel.swift
close #319 
<br/>
비로그인시 홈뷰 내 유저 접근 제한 기능 구현했습니다. 
`HomeViewModel`, `HomeViewController` 내 코드 정리 했습니다. 
<br/>
이전에 `HomeViewModel`, `HomeViewController`에 있던 로그인 여부에 따른 코드를 제거했습니다. 
`isLoggedIn`이라는 변수를 매개변수로 넘겨주었는데, 이미 `APIConstants`에 정의되어있었어서 제거했습니다. 
이전 PR에서는 검색뷰 접근도 제한했는데 확인해보니, 작품상세뷰도 비로그인시 넘어갈 수 있어서 열어두었습니다. 
1. `Presentation` > `Base` > `InduceLogin` 폴더에 로그인 유도 모달뷰와 뷰컨트롤러를 추가했습니다. 
2. `UIViewController+` 익스텐션에 해당 뷰컨을 `present`, `dismiss` 하는 함수를 구현했습니다. 
```
func presentInduceLoginViewController() {
let viewController = InduceLoginViewController()
viewController.modalPresentationStyle = .overFullScreen
self.present(viewController, animated: false)
}
func dismissViewController() {
self.dismiss(animated: false)
}
```
3. `InduceLoginViewController` 에는 버튼 탭 이벤트 두개만 있어서 따로 뷰모델을 생성하지 않고 바로 …
> [Feat] #319 - 비로그인시 홈뷰 내 유저 접근 제한 기능 구현

- WSSiOS/WSSiOS.xcodeproj/project.pbxproj
- WSSiOS/WSSiOS/App/SceneDelegate.swift
- WSSiOS/WSSiOS/Network/Auth/AuthService.swift
- WSSiOS/WSSiOS/Network/Avatar/AvatarService.swift
- WSSiOS/WSSiOS/Network/Blocks/BlocksService.swift
- WSSiOS/WSSiOS/Network/Feed/FeedDetailService.swift
- WSSiOS/WSSiOS/Network/Feed/FeedService.swift
- WSSiOS/WSSiOS/Network/Foundation/APIConstants.swift
- WSSiOS/WSSiOS/Network/Foundation/Networking.swift
- WSSiOS/WSSiOS/Network/Foundation/TokenCheckURLProtocol.swift
- WSSiOS/WSSiOS/Network/Foundation/WSSURLProtocol.swift
- WSSiOS/WSSiOS/Network/Keyword/KeywordService.swift
- WSSiOS/WSSiOS/Network/Memo/MemoService.swift
- WSSiOS/WSSiOS/Network/Notice/NoticeService.swift
- WSSiOS/WSSiOS/Network/Novel/NovelService.swift
- WSSiOS/WSSiOS/Network/NovelDetail/NovelDetailService.swift
- WSSiOS/WSSiOS/Network/NovelReview/NovelReviewService.swift
- WSSiOS/WSSiOS/Network/Onboarding/OnboardingService.swift
- WSSiOS/WSSiOS/Network/Recommend/RecommendService.swift
- WSSiOS/WSSiOS/Network/Search/SearchService.swift
- WSSiOS/WSSiOS/Network/User/UserService.swift
- WSSiOS/WSSiOS/Network/UserNovel/UserNovelService.swift
- WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
- WSSiOS/WSSiOS/Resource/Constants/URLs/URLs.swift
- WSSiOS/WSSiOS/Source/Data/DTO/AuthResult.swift
- WSSiOS/WSSiOS/Source/Presentation/Login/LoginViewController/LoginViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/Login/LoginViewModel/LoginViewModel.swift
close #321 
<br/>
- 자동 로그인을 구현합니다.
- 401 에러시 refresh Token으로 refresh & access Token을 자동으로 재발급 시도를 하며, 재발급에 실패할 경우 로그인 화면으로 이동합니다.
<br/>
- APIConstants 의 타입 프로퍼티들을 수정하여 구현했습니다. 
- isTesting 값을 true나 false로 바꾸어서 사용할 토큰 값을 정합니다! 더 자세하게 설명하자면,
- testToken은 Config에 저장해둔 토큰 값을 가져옵니다.
- accessToken은 isTesting 값에 따라서 testToken을 가져오거나, UserDefaults의 실제 accessToken 값을 가져옵니다.
- isLogined는 이 accessToken 값이 비어있는지에 따라 이미 로그인한 유저인지 아닌지 판단할 수 있게 합니다.
```swift
struct APIConstatns {
// Config의 Test Token을 사용한다면, 이 값을 true로,
// UserDefaults의 실제 토큰 값을 쓰려면 이 값을 false로 바꿀 것.
static let isTesting: Bool = true
static var isLogined: Bool {
!accessToken.isEmpty
}
static var accessToken: String {
isTesting ? testToken : UserDefaults.standard.value(forKey: StringLiterals.UserDefault.accessToken) as? String ?? ""
} …
```
> [Network] #321 - 자동 로그인, 401 대응 토큰 재발급 구현

- WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeView/HomeAssistantView/HomeInterestView.swift
- WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeView/HomeCell/HomeInterestCollectionViewCell.swift
- WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeView/HomeCell/HomeTasteRecommendCollectionViewCell.swift
- WSSiOS/WSSiOS/Source/Presentation/Search/NormalSearch/NormalSearchViewController/NormalSearchViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/Search/NormalSearch/NormalSearchViewModel/NormalSearchViewModel.swift
close #342 
<br/>
- 일반탐색: `isFetching` 변수를 추가하여 무한스크롤 중복 요청 방지 반영했습니다.
- 홈뷰: 관심글 내 상황에 대한 타이틀 분기처리를 수정했습니다. 
- 홈뷰: 관심글 및 취향추천에서 작품평점값을 소수점 첫째자리에서 반올림한 값이 보여지도록 수정했습니다. 
<br/>
네트워크 요청이 진행 중일떄에는 이외의 데이터가 fetching 되지 않도록 `isFetching` 이라는 변수를 추가했습니다. 
하쿠야고마워~
<br/>
- 홈뷰 관심글 수정사항 반영
비로그인일 때 : 관심글
유저의 관심작품이 없을 때: \(유저 닉네임)님의 관심글
관심작품은 있으나 그에 해당하는 글이 없을 때: 관심글 
https://github.com/user-attachments/assets/b0de1813-0222-48e8-aecc-6f8dddf787fa
<br/>
<br/>
<br/>
> [Fix] #342 - 일반탐색 내 무한스크롤 로직 수정 | 홈뷰 내 UI 디테일 반영

- WSSiOS/WSSiOS/Source/Presentation/Login/LoginViewModel/LoginViewModel.swift
close #378 
<br/>
- 리젝사유인 카카오톡 미설치시 카카오계정 로그인을 구현합니다.
<br/>
- 아주 약간의 수정만 있습니다.
- 
<br/>
- 카카오 계정 로그인
<br/>
- 카카오톡 설치 여부를 확인하고, 카카오톡이 없는 경우 카카오 계정 로그인이 가능하도록 수정했습니다.
<br/>
- 카카오 개발자 공식 문서
<br/>
> [Fix] #378 - 카카오톡 설치 안된 경우 카카오 계정 로그인 되도록 구현

- WSSiOS/WSSiOS.xcodeproj/project.pbxproj
- WSSiOS/WSSiOS/Info.plist
- WSSiOS/WSSiOS/Network/User/UserService.swift
- WSSiOS/WSSiOS/Resource/Constants/Config/Config.swift
- WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
- WSSiOS/WSSiOS/Resource/Constants/URLs/URLs.swift
- WSSiOS/WSSiOS/Resource/Extensions/UIViewController+.swift
- WSSiOS/WSSiOS/Source/Data/DTO/AppVersionResult.swift
- WSSiOS/WSSiOS/Source/Data/Repository/UserRepository.swift
- WSSiOS/WSSiOS/Source/Presentation/Base/AlertButton/WSSAlertViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeViewController/HomeViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeViewModel/HomeViewModel.swift
- close #387 
<br/>
- 앱 최소버전보다 작을 시 앱 강제 업데이트 기능 구현했습니다. 
<br/>
레퍼런스 찾아보니까 앱스토어 아이디는 대체로 숨기더라고요! 
Debug, Release Config 파일 내에 추가해주시면 됩니다. (카톡 확인 ♡)
앱 버전 업데이트 알럿이 뜰 때에는 업데이트 하기 전까진 계속 알럿이 떠야해서 버튼을 선택하면 `dismiss`되게 하는 걸 선택적으로 적용될 수 있도록 변수를 추가했습니다. 
```
final class WSSAlertViewController: UIViewController {
//MARK: - Properties
private var isDismissable: Bool
private func bindGesture() {
rootView.leftButton.rx.tap
.throttle(.seconds(3), latest: false, scheduler: MainScheduler.instance)
.bind(with: self, onNext: { owner, _ in
owner.leftButtonTapSubject.onNext(())
print("\(String(describing: owner.leftTitle))Button Tap 💖")
if owner.isDismissable {
owner.dismiss(animated: true)
}
})
.disposed(by: disposeBag)
rootView.rightButton.rx.tap
.throttle(.seconds(3), latest: false, scheduler: …
```
> [Feat] #387 - 앱 최소버전보다 작을 시 앱 강제 업데이트 기능 구현 

- WSSiOS/WSSiOS/Source/Presentation/FeedEdit/FeedEditView/FeedEditAssistantView/FeedEditContentView.swift
- close #399 
<br/>
수다글 작성 시 커서를 글 중간에 두고 엔터를 입력하면 커서가 맨 끝으로 이동하는 오류가 있어 해결했습니다. 
<br/>
textView의 text를 업데이트하면 커서가 자동으로 텍스트의 맨 끝으로 이동한다고 합니다. 
따라서 텍스트를 업데이트하기 전 커서 위치를 저장해두었다가
텍스트 업데이트 후 커서 위치를 복원하는 방식으로 해결했습니다. 
https://github.com/Team-WSS/WSS-iOS/blob/1427c68c55032049de7a01283a3bb295ad373b61/WSSiOS/WSSiOS/Source/Presentation/FeedEdit/FeedEditView/FeedEditAssistantView/FeedEditContentView.swift#L144-L154
<br/>
<br/>
<br/>
<br/>
> [Fix] #399 - 수다글 엔터 키 입력 시 커서가 맨 끝으로 이동하는 문제 해결

- WSSiOS/WSSiOS/Source/Presentation/Search/Search/SearchViewController/SearchViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/Search/Search/SearchViewModel/SearchViewModel.swift
- close #397 
<br/>
- 소소픽 데이터 조회 실시간 반영되도록 수정했습니다. 
- SearchVC 내 viewWillDisappear 코드 제거 했습니다. 
<br/>
기존에 Notification 코드를 짜면서 `addObserver` 를 할용할 때 작성해두었던 메모리 해제 코드를 다 지우지 않았던 것 같습니다. 
지금은 `rx.notification` 을 활용하여 `.disposed(disposeBag)` 로 메모리 해제를 하고 있어서 해당 코드가 필요 없다는 판단에 삭제했습니다 !
```swift
override func viewWillDisappear(_ animated: Bool) {
super.viewWillDisappear(animated)
NotificationCenter.default.removeObserver(self)
}
```
<br/>
<br/>
<br/>
<br/>
> [Fix] #397 - 소소픽 데이터 조회 실시간 반영되도록 수정 

- WSSiOS/WSSiOS.xcodeproj/project.pbxproj
- WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
- WSSiOS/WSSiOS/Resource/Extensions/UIViewController+.swift
- WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailAssistantView/FeedDetailUnknownUserErrorView.swift
- WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailView.swift
- WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailViewController/FeedDetailUnknownUserErrorViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailViewController/FeedDetailViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailViewModel/FeedDetailViewModel.swift
- WSSiOS/WSSiOS/Source/Presentation/Search/DetailSearch/DetailSearchViewController/DetailSearchViewController.swift
- close #376 
<br/>
- 삭제된 글 클릭 시 모달 Alert 기능 구현했습니다. 
<br/>
기존 `WSSAlertViewController` 를 사용하려 했는데, 폰트가 달라서 그냥 새로 하나 만들었습니다. 좀 더 좋은 방법이 있었을까요.. 🥲
<br/>
알럿 내 확인 버튼 클릭 시 모달 dismiss와 동시에 FeedDetailVC pop을 해야하므로` rx.notification`을 적용했습니다. 
``` swift 
// FeedDetailUnknownUserErrorViewController.swift
rootView.confirmationButton.rx.tap
.debounce(.milliseconds(300), scheduler: MainScheduler.instance)
.bind(with: self, onNext: { owner, _ in
NotificationCenter.default.post(name: owner.popFeedDetailViewControllerNotificationName,
object: nil)
owner.dismiss(animated: true)
})
.disposed(by: disposeBag)
```
<br/>
`.materialize`: onNext, onError, onCompleted를 Event로 래핑
기존 subscribe 에 있는 onNext, onError 로 이벤트를 처리했을 때보다 훨씬 명확하게 이벤트 처리를 할 수 있고 가독성이 높아집니다. 
또한, onError 발생 시에는 스트림이 종료되지만 위 오퍼레이터를 사용 시 스트림이 …
> [Fix] #376 - 삭제된 글 클릭 시 모달 Alert 기능 구현 

- WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewModel/MyPageViewModel.swift
- close #408 
<br/>
피드에서 최근 5개를 불러와야 하는데 오래된 5개를 불러오는 에러가 발생하였습니다.
따라서 suffix 로 구현된 코드를 prefix 로 수정하였습니다.
단순히 코드만 고치니 아래와 같은 에러가 났습니다.
따라서 ArraySlice 가 무엇인지 공식문서를 찾아보았습니다.
ArraySlice는 새로운 메모리를 사용하지 않고 본래의 Array 값을 사용하여, 별도의 메모리 할당 없이 빠른 접근이 가능하다고 합니다.
차이점은 Array는 index 0부터 시작하지만, ArraySlice는 index 1부터 시작하기 때문에 잘못 접근하면 fatal error 가 날 수 있다는 것이죠 
<br/>
**- 그렇다면 에러가 발생한 이유 뇌피셜**
suffix 는 뒤에서부터 순서를 매기기 때문에 기존의 index 0 값을 첫 번째 값으로 접근하지 않게 됨, prefix 는 앞에서부터 순서를 매기기 때문에 index 0 값을 무조건 첫 번째 값으로 접근하게 됨. 
그렇기 때문에 suffix 는 ArraySlice 값이더라도 Array 로 자동변환이 가능하지 않을까? prefix 는 꼭 Array 로 명시해주어야 하는 것이고 ,,,?
<br/>
**- 코드 확인**
- suffix 는 ArraySlice / Array 사용을 선택 가능한 것 같음
- prefix 는 ArraySlice 로만 사용
<br/>
https://developer.apple.com/documentation/swift/arrayslice …
> [Fix] #408 - MyPage 피드 카테고리 뒤에서부터 5개가 뜨는 에러 해결

- WSSiOS/WSSiOS/Resource/Extensions/UIViewController+.swift
- WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeViewController/HomeViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeViewModel/HomeViewModel.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewController/MyPageViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewModel/MyPageEditProfileViewModel.swift
- close #376 
<br/>
- EditView 를 진입하는 경로를 2가지로 구분하였습니다 (홈/마이페이지)
- 다른 요소를 선택하고 저장할시 선택했던 장르가 초기화되는 에러를 해결하였습니다.
<br/>
<br/>
진입 경로를 ViewController 에서 해야할 지, ViewModel 에서 해야할 지 고민했는데 로직처리라고 생각하여 ViewModel 에서 하기로 하였습니다:)
따라서 myPage 에서 Edit 으로 넘어갔을 때 GET /users/my-profile API 는 호출되지 않습니다.
```swift
enum MyPageEditEntryType {
case myPage
case home
}
init(userRepository: UserRepository,
entryType: MyPageEditEntryType,
profileData: MyProfileResult? = nil) {
self.userRepository = userRepository
self.entryType = entryType
self.profileData = profileData
}
```
<br/>
| 홈에서 진입시 | 마이페이지에서 진입시 |
|---|---|
|![Simulator Screen Recording - iPhone 16 - 2025-01-01 at 20 47 13](https://github.com/user-attachments/assets/c814a784-b169-4595-94ae-28164592c530)|![Simulator Screen Recording - iPhone 16 - 2025-01-01 …
> [Feat] #376 - MyPageEditView 진입 분기처리 및 장르 미선택시 에러 해결

- WSSiOS/WSSiOS/Source/Presentation/FeedEdit/FeedEditView/FeedEditAssistantView/FeedEditContentView.swift
- close #411 
<br/>
FeedEditView 이모지 깨지는 문제 해결
<br/>
**원인**
- 기존에 커서 위치를 복원하기 위해 selectedRange.location 과 feedContent.count 를 사용함.
(#400 참고.)
- 커서 위치를 복원할 때 사용하는 `selectedRange.location` 은 **UTF-16 인덱스**를 기반으로 커서 위치를 반환.
- `feedContent.count` 는 Swift String의 Character 개수(**유니코드 스칼라**)를 반환.
- UTF-16과 유니코드 스칼라 간의 차이로 인해 커서 위치가 정상적으로 복원되지 않으면서 조합문자인 이모지가 분리되는 현상 발생.
**해결**
- 커서 복원 작업을 UITextView의 UITextPosition 및 offset(from:to:) 메서드를 활용하여 UTF-16 인덱스를 기준으로 작업하도록 변경.
<br/>
<br/>
행간/자간 적용을 위해 AttributedString를 사용하면서 이런 문제들이 많이 발생하네요..
AttributedString 안 쓰고 행간/자간 적용하는 방법은 없나?
<br/>
<br/>
> [Fix] #411 - FeedEditView 이모지 깨지는 문제 해결

- WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileView/MyPageFeedView.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewController/MyPageFeedDetailViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewController/MyPageViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewModel/MyPageViewModel.swift
- close #425 
<br/>
마이페이지 내 활동 디테일 에러를 수정하였습니다.
<br/>
- 활동 더보기 버튼 초기값을 False 로 부여하였습니다.
- 활동 상세 뷰를 터치없이도 보여지도록 수정하였습니다.
- 활동에 Cell Data 를 서버에서 전달받고 있는데,  별점이 반올림되지 않고 있어서 서버측에 요청 넣어두었습니다!
| 활동 더보기 버튼 | 활동 디테일뷰 |
|---|---|
<br/>
더보기버튼이 잘 안뜨는 이슈는 재현하기가 어렵네요!
코드 상으로는 무조건 서버 연결이 되어야지 버튼이 보이는 방식이라 문제 없을 것 같습니다 :)
<br/>
> [Fix] #425 - MyPageFeedDetail 에러 수정

- WSSiOS/WSSiOS/Resource/Extensions/UIViewController+.swift
- close #429 
<br/>
- QA에서 발견한 네비게이션 바가 화면 전환 시 뒤늦게 사라지는 오류 수정
<br/>
- 네비게이션 바 세팅 메서드 setWSSNavigationBar가 매번 navigationController? 로 접근해서 전역 Appearance를 변경하는데, 이런 경우 뷰 컨트롤러 전환 애니메이션 중에는 네비게이션 바가 변경사항에 반응하지 않아 딜레이가 생기는 게 문제가 아니었을까 생각했습니다. . . 
- 그래서 setWSSNavigationBar 메서드가 VC 각각의 설정만 변경하도록 수정했더니 딜레이가 없어졌습니다!
<br/>
- 아이폰 15 Pro 실기기
https://github.com/user-attachments/assets/e8e6765c-ba67-4a53-925c-1d11fca833e8
<br/>
- 분명 시뮬에서는 오류가 없었는데, 실 기기에서는 모든 화면 전환에서 발생하는 오류였네요. 실 기기 테스트의 중요성을 배웁니다.
<br/>
<br/>
> [Fix] #429 -2 - 네비게이션 바가 화면 전환 시 뒤늦게 사라지는 오류 수정

- WSSiOS/WSSiOS/Resource/Extensions/UIViewController+.swift
- WSSiOS/WSSiOS/Source/Presentation/Library/LibraryViewController/LibraryViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/Library/LibraryViewModel/LibraryViewModel.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileView/ProfileAssistantView/MyPageInventoryView.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewController/MyPageViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewModel/MyPageViewModel.swift
- close #451 
<br/>
- 영역 별 터치시 해당 상태로 이동하도록 구현
- 화살표 이미지 터치 안되는 에러 해결
<br/>
- 보관함 터치 영역을 섹션 별로 부여하였습니다.
<br/>
1. MyPageInventoryView 에서 Section 별 영역을 기존에는 stackView 로 구현하였지만 이를 UIView 로 바꾸었습니다. 
+Section 별 뷰를 구현할 때 tag 값을 부여하여 터치시 이를 가져올 수 있도록 하였습니다.
```swift
private func createInventorySectionView(tag: Int, countLabel: UILabel, textLabel: UILabel, text: String, addLine: Bool = false) -> UIView {
let statusView = UIView()
statusView.do {
$0.tag = tag
}
countLabel.do {
$0.applyWSSFont(.title2, with: "0")
$0.textAlignment = .center
}
textLabel.do {
$0.applyWSSFont(.body5, with: text)
$0.textColor = .wssGray200
$0.textAlignment = .center
}
statusView.addSubviews(countLabel,
textLabel)
countLabel.snp.makeConstraints {
$0.top.equalToSuperview().inset(13.5)
$0.centerX.equalToSuperview()
} …
```
> [Feat] #451 - 보관함 상태 탭시 특정 위치로 이동 및 에러 수정

- WSSiOS/WSSiOS.xcodeproj/project.pbxproj
- WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileView/MyPageEditProfileView.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewController/MyPageEditProfileViewController.swift
- close #426 
<br/>
~attributedText 를 사용하니 부분 드래그가 안되는 에러가 발생하여 기본 Font 를 사용하였습니다.~
=> 업데이트 함수 내에 applyWSSFont 를 작성해두니, 업데이트 될때마다 makeAttribute 되어 텍스트 전체를 다시 렌더링하여 커서 위치를 찾을 수 없는 에러를 확인하였습니다.
효원이가 해결한 에러와도 같습니다.
하지만 초기 데이터 바인딩할때 (bindData 함수) font 를 적용해두면, [typingattributes](https://developer.apple.com/documentation/uikit/uitextfield/typingattributes) 속성으로 인해 텍스트가 업데이트 될 때마다 따로 makeAttribute 속성을 호출하지 않아도 폰트가 적용될 수 있음을 알게 되었습니다.
<br/>
- TextField 
textField 의 lineHeight 가 잘 적용되지 않아 font 를 지정해주고, (수정 전) 처음 값을 연결시켜주는 bindData 함수 호출 시 makeAttribute 를 사용하였습니다.
```swift
nicknameTextField.do {
$0.font = .Body2
$0.textColor = .wssBlack
$0.tintColor = .wssBlack
$0.contentVerticalAlignment = .center
}
/// 수정 전 처음 데이터 연결시켜줄 때 
func bindData(data: MyProfileResult) { …
```
> [Fix] #426 - MyPageEditView 텍스트 드래그로 부분 선택 안되는 에러 해결

- WSSiOS/WSSiOS.xcodeproj/project.pbxproj
- WSSiOS/WSSiOS/Network/Notification/NotificationService.swift
- WSSiOS/WSSiOS/Resource/Constants/URLs/URLs.swift
- WSSiOS/WSSiOS/Source/Data/Repository/NotificationRepository.swift
- WSSiOS/WSSiOS/Source/Presentation/Home/HomeNotice/HomeNoticeViewModel/HomeNoticeViewModel.swift
- close #466 
<br/>
- 피드 관련 공지사항을 클릭했을 때 알림 읽음 처리가 될 수 있도록 하는 POST API 연결 했습니다. 
<br/>
각 공지사항의 상태에 따른 분기처리를 `HomeNoticeVM`에서 처리해주었습니다. 
**1. 공지사항일 때 -> 공지사항 상세뷰로 이동**
**2. 이미 읽은 공지사항일 때 -> 별도의 서버 요청 없이 피드 상세뷰로 이동**
ㄴ 이때에 공지사항은 자체적으로 서버에서 읽음 처리를 해주나, 피드 관련 공지사항은 따로 클라에서 post를 해줘야 하기 때문
**3. 이외의 상황일 때 (읽지 않았고 피드 관련 공지사항일 때) -> 읽음 처리 API POST 후 피드 상세뷰로 이동** 
```swift
input.noticeTableViewCellSelected
.map { indexPath -> NotificationEntity in
return self.notificationList.value[indexPath.row]
}
.subscribe(with: self, onNext: { owner, notification in
let notificationId = notification.notificationId
guard let feedId = notification.feedId else { return }
if notification.isNotice {
owner.pushToNoticeDetailViewController.accept(notificationId)
} else if notification.isRead { …
```
> [Feat] #466 - 피드 관련 공지사항 알림 읽음 처리 API 구현 

- WSSiOS/WSSiOS/Source/Presentation/Home/HomeNotification/HomeNotificationViewModel/HomeNotificationViewModel.swift
- close #481 
<br/>
- 공지사항 무한스크롤이 안되는 이슈를 해결했습니다. 
<br/>
lastNotificationId를 단순한 데이터의 개수로 증가시켰습니다. 
```swift
lastNotificationId += data.notifications.count
```
이전 방식의 문제점: 모든 알림이 모든 유저에게 다 동일하게 전달되지 않는다.
EX) 이나는 400번 알림을 받고 구리스는 400번 알림을 받지 않음.
따라서 일정한 개수만큼 `lastNotificationId`를 증가시키면 구리스는 400번이 없기 때문에 빈 배열이 전달된다.
**-> 받아온 마지막 데이터의 notificationId를 받아 넣어주도록 수정했습니다.** 
```swift
if let lastNotification = data.notifications.last {
self.lastNotificationId = lastNotification.notificationId
}
```
<br/>
<br/>
이전의 무한스크롤은 count로 넣어줘서 잘될거라 생각했는데...!
상황 케이스를 잘 생각해서 코드를 짜야 할 것 같네요 ㅜㅜ 반성했습니다..
<br/>
X
<br/>
> [Fix] #481 - 공지사항 무한스크롤 작동되지 않는 이슈 해결

- WSSiOS/WSSiOS/Network/Auth/AuthService.swift
- WSSiOS/WSSiOS/Network/Foundation/TokenCheckURLProtocol.swift
- WSSiOS/WSSiOS/Source/Presentation/Base/ServiceTermAgreement/ServiceTerm.swift
- close #476 
<br/>
- 404 처리가 잘못되어서, 회원 탈퇴가 아닌 404 에러에도 모두 로그인 화면으로 돌아가는 오류 해결
- 약관 동의 화면 UX 라이팅 변경
<br/>
- 404 에러가 오면, 다른 일반 API를 호출하여 실제로 회원 탈퇴를 했는지 확인하도록 했는데, 이때 기존 서비스에 있는 API 를 사용해 호출하였기 때문에 해당 API 도 다시 404 에러가 떠서 또 동일한 API를 호출하는 무한 재귀에 빠지는 오류가 있었습니다. 
- 해당 오류 때문에 QA 때는 일단 404면 다 로그인으로 돌아가도록 했더니, 회원 탈퇴를 한 경우가 아닐 때에도 로그인으로 돌아가는 현상이 생겼습니다.
- 토큰체크URL Session을 사용하지 않는 토큰 리이슈 API를 사용하면 회원 탈퇴 여부를 확인하면서도 무한 재귀에 빠지지 않기 때문에, 일단 401 때와 동일하게 처리하도록 수정했습니다.
<br/>
<br/>
<br/>
<br/>
> [Hotfix] #476 - 2차 스프린트 1차 QA 사항 수정
