Team-WSS/WSS-iOS

- WSSiOS/WSSiOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> [Fix] #4 - 깃 충돌 해결 (swiftPM)

- WSSiOS/WSSiOS.xcodeproj/project.pbxproj
- WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
- WSSiOS/WSSiOS/Source/Presentation/Base/WSSTabBarController.swift
- WSSiOS/WSSiOS/Source/Presentation/Base/WSSTabBarItem.swift
<br/>
<br/>
<br/>
```swift
abc
```
<br/>
<br/>
<br/>
<br/>
> [Add] #16 - TabBar 코드 추가

- README.md
> [Fix] #20 - README 추가

- WSSiOS/WSSiOS.xcodeproj/project.pbxproj
- WSSiOS/WSSiOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- WSSiOS/WSSiOS/Source/Presentation/Memo/MemoView/MemoAssistantView/MemoCreateContentView.swift
- WSSiOS/WSSiOS/Source/Presentation/Memo/MemoView/MemoAssistantView/MemoEditContentView.swift
- WSSiOS/WSSiOS/Source/Presentation/Memo/MemoView/MemoAssistantView/MemoHeaderView.swift
- WSSiOS/WSSiOS/Source/Presentation/Memo/MemoView/MemoCreateView.swift
- WSSiOS/WSSiOS/Source/Presentation/Memo/MemoView/MemoEditView.swift
- WSSiOS/WSSiOS/Source/Presentation/Memo/MemoViewController/MemoCreateViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/Memo/MemoViewController/MemoEditViewController.swift
#35
<br/>
MemoView UI 구현
<br/>
이전 pr과 동일한 pr 입니당
<br/>
> [Design] #35 - MemoView UI 구현

- WSSiOS/WSSiOS/Info.plist
- WSSiOS/WSSiOS/Network/Foundation/APIConstants.swift
- WSSiOS/WSSiOS/Network/Foundation/Networking.swift
closed #58 
<br/>
- 네트워크 추가 세팅 완료했습니다 
<br/>
- info.plist 파일 수정
- Bundle.main.object로 묶기
- testToken값 설정
<br/>
- 없습니다
<br/>
- Config 파일은 각자 수정해주심 됩니당
<br/>
- 레츠고 효원전, 지원신
<br/>
> [Setting] #58 - 네트워크 추가 세팅 

- WSSiOS/WSSiOS.xcodeproj/project.pbxproj
- WSSiOS/WSSiOS/Network/UserNovel/UserNovelService.swift
- WSSiOS/WSSiOS/Source/Data/DTO/UserNovelDTO.swift
- WSSiOS/WSSiOS/Source/Data/DTO/UserNovelResult.swift
- WSSiOS/WSSiOS/Source/Data/Repository/UserNovelRepository.swift
- WSSiOS/WSSiOS/Source/Presentation/DeletePopup/DeletePopupView.swift
- WSSiOS/WSSiOS/Source/Presentation/DeletePopup/DeletePopupView/DeletePopupAssistantView/DeletePopupContentView.swift
- WSSiOS/WSSiOS/Source/Presentation/DeletePopup/DeletePopupViewController/DeletePopupViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/Memo/MemoViewController/MemoCreateViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/Memo/MemoViewController/MemoEditViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailHeaderView.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoPlatformView.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoRatingView.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoReadDateView.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoView.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailMemoSettingButtonView.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailMemoView.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailView.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailViewController/NovelDetailViewController.swift
#57
<br/>
NovelDetailView 내 API 연결 완료했습니다!
<br/>
- getUserNovel API 연결 완료
- deleteUserNovel API 연결 완료
- 배경 블러 이미지 구현
- navigation bar 추가
- navigation bar 소설 삭제/수정 버튼 추가, 기능 구현
<br/>
<br/>
소설 삭제 후 로직은 뷰 연결 후 추가 예정입니당
<br/>
<br/>
> [Network] #57 - NovelDetailView API 연결

- WSSiOS/WSSiOS/Network/User/UserService.swift
- WSSiOS/WSSiOS/Source/Data/Repository/UserRepository.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageCell/MyPageInventoryCollectionViewCell.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageCell/MyPageSettingCollectionViewCell.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageCustomModalViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageInfoViewController.swift
#73 
<br/>
UserService 파일에서 오류가 나 수정하였습니다~
<br/>
#closed #73
> [Fix] #73 - 파일 수정

- WSSiOS/WSSiOS.xcodeproj/project.pbxproj
- WSSiOS/WSSiOS/Resource/Extensions/UITextView+.swift
- WSSiOS/WSSiOS/Source/Presentation/Base/WSSToastView.swift
- WSSiOS/WSSiOS/Source/Presentation/DeletePopup/DeletePopupView/DeletePopupAssistantView/DeletePopupContentView.swift
- WSSiOS/WSSiOS/Source/Presentation/DeletePopup/DeletePopupViewController/DeletePopupViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/Memo/MemoView/MemoAssistantView/MemoEditContentView.swift
- WSSiOS/WSSiOS/Source/Presentation/Memo/MemoView/MemoAssistantView/MemoHeaderView.swift
- WSSiOS/WSSiOS/Source/Presentation/Memo/MemoView/MemoAssistantView/MemoReadContentView.swift
- WSSiOS/WSSiOS/Source/Presentation/Memo/MemoViewController/MemoEditViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/Memo/MemoViewController/MemoReadViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailCreateMemoView.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailHeaderView.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoDescriptionView.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoGenreView.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoKeywordView.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoPlatformView.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoRatingView.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoReadDateView.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoReadStatusTagView.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoReadStatusView.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailMemoView.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailCell/NovelDetailInfoKeywordCollectionViewCell.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailCell/NovelDetailInfoPlatformCollectionViewCell.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailCell/NovelDetailMemoTableViewCell.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailView.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailViewController/NovelDetailViewController.swift
#71
<br/>
NovelDetail, Memo 세부 기능 구현완료햇씁니다.
<br/>
- 소설 디테일 navigation bar 스타일 적용
- 소설 디테일 탭 sticky header 적용
- 뷰 이동, 토스트 표시 적용 완료
- UILabel, UITextView 자간 행간 적용 완료
<br/>
<br/>
<br/>
<br/>
> [Feat] #71 - NovelDetail, Memo 세부 기능 구현

- WSSiOS/WSSiOS/Source/Presentation/Library/LibraryViewController/LibraryViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalViewController/RegisterNormalViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/Register/RegisterSuccess/RegisterSuccessViewController/RegisterSuccessViewController.swift
#85
<br/>
동일 방식으로 "작품에 메모 남기기" 버튼 구현했습니다
<br/>
<br/>
<br/>
<br/>
<br/>
> [Fix] #85 - 작품 등록 후 메모 남기기 버튼 클릭 시 메모 뷰로 이동

- WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
- WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalNovelSummaryView.swift
- WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalPlatformView.swift
- WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalReadDateView.swift
- WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalReadStatusView.swift
- WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalView.swift
- WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalViewController/RegisterNormalViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/Register/RegisterSuccess/RegisterSuccessViewController/RegisterSuccessViewController.swift
#89 
<br/>
platform 버튼 사라진 문제를 발견해 수정합니다.
<br/>
platform 버튼 사라진 것 수정, 네비게이션 바 아래의 DividerView 추가
<br/>
<br/>
-hotfix 같은 느낌으로 가볍게 리뷰 부탁드립니당
<br/>
<br/>
> [Fix] #94 - platform 버튼 사라진 것 수정, 네비게이션 바 아래의 DividerView 추가

- WSSiOS/WSSiOS/Source/Presentation/Library/LibraryViewController/LibraryBaseViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/Library/LibraryViewController/LibraryViewController.swift
#86 
<br/>
코드리뷰 반영한 것을 푸쉬안하고 머지해버려서 다시 팝니둥
<br/>
> [Fix] #86 - 코드리뷰 반영 수정

- WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeAssistantView/HomeCharacterView.swift
- WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeView.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/Record/RecordView/RecordCell/RecordTableViewCell.swift
#99 
<br/>
- Mypage Navigation 배경 변경, 기기대응 추가
<br/>
- Mypage Navigation 배경 흰색으로 변경
- Home View 기기대응 추가
<br/>
<br/>
<br/>
<br/>
> [Fix] #99 - Mypage Navigation 배경 변경, 기기대응 추가

- WSSiOS/WSSiOS/Info.plist
- WSSiOS/WSSiOS/Network/Foundation/APIConstants.swift
- WSSiOS/WSSiOS/Resource/Constants/Config/Config.swift
close #113 
<br/>
새로 발급된 테스트 토큰을 추가하였습니다.
<br/>
태스트 토큰 그대로 두는게 거슬려서 Config 에 넣어두었습니당.
코드는 아래 !
카톡방 확인해서 반영 부탁드려용
<br/>
```swift
static let testToken = Bundle.main.object(forInfoDictionaryKey: Config.Keys.Plist.testToken) as? String ?? ""
```
<br/>
> [Setting] #113 - TestToken 추가

- WSSiOS/WSSiOS/Network/UserNovel/UserNovelService.swift
- WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
- WSSiOS/WSSiOS/Resource/Constants/URLs/URLs.swift
- WSSiOS/WSSiOS/Resource/Extensions/UIViewController+.swift
- WSSiOS/WSSiOS/Source/Presentation/Library/LibraryViewController/LibraryViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailCreateMemoView.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailHeaderView.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoDescriptionView.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoGenreView.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoKeywordView.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoPlatformView.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoRatingView.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoReadDateView.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoReadStatusTagView.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoReadStatusView.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoView.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailMemoSettingButtonView.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailMemoView.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailTabView.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailCell/NovelDetailInfoKeywordCollectionViewCell.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailCell/NovelDetailInfoPlatformCollectionViewCell.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailCell/NovelDetailMemoTableViewCell.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailView.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailViewController/NovelDetailViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalViewController/RegisterNormalViewController.swift
#111
<br/>
NovelDetailView 리팩토링 했습니다
<br/>
- 멘토님 피드백 바탕으로 리팩토링 진행했씁니다
- 마크주석 수정했씁니다
- table/collectionview rx로 다시 구현했씁니다
<br/>
없씀
<br/>
혹시나 놓친 부분이 있다면 알려주세오!
<br/>
<br/>
> [Refactor] #111 - NovelDetailView Refactor

- WSSiOS/WSSiOS/Source/Presentation/Base/WSSMainButton.swift
- WSSiOS/WSSiOS/Source/Presentation/Base/WSSSectionTitleView.swift
- WSSiOS/WSSiOS/Source/Presentation/Base/WSSTabBarController.swift
- WSSiOS/WSSiOS/Source/Presentation/Base/WSSTabBarItem.swift
- WSSiOS/WSSiOS/Source/Presentation/Base/WSSToastView.swift
- WSSiOS/WSSiOS/Source/Presentation/Library/LibraryView/LibraryAssistantView/LibraryDescriptionView.swift
- WSSiOS/WSSiOS/Source/Presentation/Library/LibraryView/LibraryAssistantView/LibraryEmptyView.swift
- WSSiOS/WSSiOS/Source/Presentation/Library/LibraryView/LibraryAssistantView/LibraryListView.swift
- WSSiOS/WSSiOS/Source/Presentation/Library/LibraryView/LibraryCell/LibraryCollectionViewCell.swift
- WSSiOS/WSSiOS/Source/Presentation/Library/LibraryView/LibraryCell/LibraryTabCollectionViewCell.swift
- WSSiOS/WSSiOS/Source/Presentation/Library/LibraryViewController/LibraryViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageAssistantView/MyPageInventoryView.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageAssistantView/MyPageModalAvatarFeatureLabelView.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageAssistantView/MyPageProfileView.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageAssistantView/MyPageSettingView.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageAssistantView/MyPageTallyReuseView.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageAssistantView/MyPageTallyView.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageCell/MyPageInventoryCollectionViewCell.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageCell/MyPageSettingCollectionViewCell.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageChangeNicknameView.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageCustomModalView.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageInfoView.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageView.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageChangeNicknameViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageCustomModalViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageInfoViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageViewController.swift
#111 
<br/>
브런치 다시 파서 에셋과 컬러 부분 반영해 주었습니다~!
<br/>
> [Refactor] #111 - Refactor LibraryView and MyPageView

- WSSiOS/WSSiOS/Network/Memo/MemoService.swift
- WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
- WSSiOS/WSSiOS/Resource/Constants/URLs/URLs.swift
- WSSiOS/WSSiOS/Resource/Extensions/UIViewController+.swift
- WSSiOS/WSSiOS/Source/Presentation/Memo/MemoView/MemoAssistantView/MemoEditContentView.swift
- WSSiOS/WSSiOS/Source/Presentation/Memo/MemoView/MemoAssistantView/MemoHeaderView.swift
- WSSiOS/WSSiOS/Source/Presentation/Memo/MemoView/MemoAssistantView/MemoReadContentView.swift
- WSSiOS/WSSiOS/Source/Presentation/Memo/MemoView/MemoEditView.swift
- WSSiOS/WSSiOS/Source/Presentation/Memo/MemoView/MemoReadView.swift
- WSSiOS/WSSiOS/Source/Presentation/Memo/MemoViewController/MemoEditViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/Memo/MemoViewController/MemoReadViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailViewController/NovelDetailViewController.swift
#111
<br/>
메모뷰 리팩토링 완료했습니다
<br/>
- 멘토님 피드백 바탕으로 리팩토링 진행했씁니다
- 마크주석 수정했씁니다
<br/>
없어용가리
<br/>
메모 수정 쪽 텍스트뷰 분기처리가 쫌 마니 복잡하고 지저분한데... 조은 의견이 있다면?!?!?!1 알려주세요!!???!?
<br/>
<br/>
> [Refactor] #111 - MemoView Refactor

- WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
- WSSiOS/WSSiOS/Source/Presentation/DeletePopup/DeletePopupView.swift
- WSSiOS/WSSiOS/Source/Presentation/DeletePopup/DeletePopupView/DeletePopupAssistantView/DeletePopupContentView.swift
- WSSiOS/WSSiOS/Source/Presentation/DeletePopup/DeletePopupViewController/DeletePopupViewController.swift
#111
<br/>
삭제 팝업 뷰 리팩토링 했습니당
<br/>
- 멘토님 피드백 바탕으로 리팩토링 진행했씁니다
- 마크주석 수정했씁니다
<br/>
없송
<br/>
간단한 뷰라 고친게 그리 많지 않네용 헤헷
<br/>
<br/>
> [Refactor] #111 - DeletePopupView Refactor

- WSSiOS/WSSiOS.xcodeproj/project.pbxproj
- WSSiOS/WSSiOS/Source/Presentation/Base/Protocol/ViewModelType.swift
#125 
<br/>
Presentation
- Base
- Protocol 폴더 생성
Protocol 폴더 안에 ViewModelType 프로토콜을 추가하였습니다
<br/>
> [Setting] #125 - ViewModelType 프로토콜 추가

- WSSiOS/WSSiOS.xcodeproj/project.pbxproj
- WSSiOS/WSSiOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- WSSiOS/WSSiOS/Resource/Extensions/UIViewController+.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageChangeNicknameViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewModel/MyPageChangeNickNameViewModel.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewModel/MyPageViewModel.swift
#125 
<br/>
늦어서 죄송합니다 !
<br/>
급하게 짜서 네이밍이 좀 더러운데 많은 조언 부탁드릴게요!
<br/>
> [Refactor] #125 - ChangeNickname MVVM 적용

- WSSiOS/WSSiOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
close #217
<br/>
- Package.resolved 파일 재업로드했습니다. 
<br/>
- 업보청산, 바보이슈. 이런 일 없도록 주의.
<br/>
<br/>
<br/>
<br/>
> [Fix] #217 - Package.resolved 파일 재업로드

- WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
- WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeView/HomeCell/HomeInterestCollectionViewCell.swift
- WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeView/HomeCell/HomeTodayPopularCollectionViewCell.swift
close #228 
<br/>
-  HomeView 내  오늘의 인기작 & 관심글 버킷 이미지 url을 활용한 서버 연결 반영했습니다. 
- 홈뷰 내 UX라이팅 변경사항 반영했습니다. 
<br/>
<br/>
<br/>
- 낙낙 최고다~
<br/>
<br/>
> [Chore] #228 - HomeView 내 버킷 이미지 url을 활용한 서버 연결 반영

- WSSiOS/WSSiOS.xcodeproj/project.pbxproj
- WSSiOS/WSSiOS/App/SceneDelegate.swift
- WSSiOS/WSSiOS/Network/User/UserService.swift
- WSSiOS/WSSiOS/Resource/Constants/URLs/URLs.swift
- WSSiOS/WSSiOS/Resource/Extensions/UIViewController+.swift
- WSSiOS/WSSiOS/Source/Data/DTO/UserNovelStatus.swift
- WSSiOS/WSSiOS/Source/Data/Repository/UserRepository.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingView/MyPageDeleteIDWarningView.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingViewController/MyPageDeleteIDWarningViewController.swift
close #239 
<br/>
탈퇴 API 같이 구현하려했는데 소셜로그인이랑 같이 작업하신다구 그래서
생각보다 너무 짧은 PR 이 되어버린 ,,, 
<br/>
<br/>
> [Network] #239 - MyPageDeleteIDWarningView API 연결

- WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
- WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeView/HomeAssistantView/HomeInterestView.swift
- WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeView/HomeCell/HomeInterestCollectionViewCell.swift
- WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeView/HomeCell/HomeTodayPopularCollectionViewCell.swift
close #255 
<br/>
- 홈뷰와 탐색뷰에 UX라이팅 수정된 사항 반영했습니다. 
<br/>
- 닉네임과 님 사이 공백 제거했습니다. 
- 관심글이 없을 때 '아직' 단어 제거했습니다. 
- 추천작품 내 띄어쓰기 수정했습니다. (추천해 드려요 -> 추천해드려요)
- 소소픽 설명글 라이팅 수정했습니다. (사람들 -> 다른 독자들)
<br/>
따로 없습니당.
<br/>
X
<br/>
X
<br/>
> [Chore] #255 - 홈뷰 및 탐색뷰 내 UX라이팅 수정사항 반영

- WSSiOS/WSSiOS.xcodeproj/project.pbxproj
- WSSiOS/WSSiOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- WSSiOS/WSSiOS/Resource/Extensions/UIViewController+.swift
- WSSiOS/WSSiOS/Source/Presentation/Library/LibraryViewController/LibraryBaseViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/Library/LibraryViewController/LibraryViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewController/MyPageViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewModel/MyPageViewModel.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingView/MyPageChangeUserInfoView.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingViewController/MyPageChangeUserBirthViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingViewController/MyPageChangeUserInfoViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingViewController/MyPageInfoViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingViewModel/MyPageChangeUserInfoViewModel.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailViewController/NovelDetailViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalBannerImageView.swift
- WSSiOS/WSSiOS/Trash/TrashNovelDetail/TrashNovelDetailView/TrashNovelDetailAssistantView/TrashNovelDetailHeaderView.swift
- WSSiOS/WSSiOS/Trash/TrashNovelDetail/TrashNovelDetailView/TrashNovelDetailView.swift
- WSSiOS/WSSiOS/Trash/TrashNovelDetail/TrashNovelDetailViewController/TrashNovelDetailViewController.swift
close #280 
<br/>
VC 로직을 수정하였습니다
<br/>
> [Fix] #280 - 로직 수정

- WSSiOS/WSSiOS.xcodeproj/project.pbxproj
- WSSiOS/WSSiOS/Network/Foundation/ServerErrorResponse.swift
- WSSiOS/WSSiOS/Network/Onboarding/OnboardingService.swift
- WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
- WSSiOS/WSSiOS/Resource/Constants/URLs/URLs.swift
- WSSiOS/WSSiOS/Resource/Helper/ModuleFactory.swift
- WSSiOS/WSSiOS/Source/Data/Base/NicknameAvailablity.swift
- WSSiOS/WSSiOS/Source/Data/DTO/OnboardingResult.swift
- WSSiOS/WSSiOS/Source/Data/Repository/OnboardingRepository.swift
- WSSiOS/WSSiOS/Source/Presentation/Base/BirthPicker/BirthPickerView.swift
- WSSiOS/WSSiOS/Source/Presentation/Base/BirthPicker/BirthPickerViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/Login/LoginViewModel/LoginViewModel.swift
- WSSiOS/WSSiOS/Source/Presentation/Onboarding/Onboarding/OnboardingView/OnboardingAssistantView/OnboardingBirthGenderView/OnboardingBirthGenderView.swift
- WSSiOS/WSSiOS/Source/Presentation/Onboarding/Onboarding/OnboardingView/OnboardingAssistantView/OnboardingNicknameView/OnboardingNicknameView.swift
- WSSiOS/WSSiOS/Source/Presentation/Onboarding/Onboarding/OnboardingViewController/OnboardingViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/Onboarding/Onboarding/OnboardingViewModel/OnboardingViewModel.swift
바보이슈 입니다.  . .
<br/>
<br/>
<br/>
```swift
abc
```
<br/>
<br/>
<br/>
<br/>
> Revert "Revert "[Network&Feat] #291 - 온보딩 API 연결 및 기능 구현""

- WSSiOS/WSSiOS/Source/Presentation/Login/LoginViewModel/LoginViewModel.swift
- WSSiOS/WSSiOS/Source/Presentation/Onboarding/Onboarding/OnboardingViewModel/OnboardingViewModel.swift
- WSSiOS/WSSiOS/Source/Presentation/Search/NormalSearch/NormalSearchViewModel/NormalSearchViewModel.swift
close #
<br/>
<br/>
<br/>
```swift
abc
```
<br/>
<br/>
<br/>
<br/>
> [Network&feat] #291 - Push 하지 못했던 수정사항 재적용

- WSSiOS/WSSiOS/Network/Feed/FeedDetailService.swift
- WSSiOS/WSSiOS/Network/User/UserService.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailFeedView/NovelDetailFeedAssistantView/NovelDetailFeedListView.swift
close #335 
<br/>
314번 PR merge 과정에서 수정치 못한 코드 반영했습니다. sorry...
<br/>
이전과 동일! 잘 돌아가는 거 확인 했습니다. 
<br/>
<br/>
<br/>
> [Fix] #335 - 314번 PR merge 과정에서 수정치 못한 코드 반영

- WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
- WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailAssistantView/FeedDetailReplyWritingView.swift
- WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailCell/FeedDetailReplyCollectionViewCell.swift
- WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailViewController/FeedDetailViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailViewModel/FeedDetailViewModel.swift
close #340 
<br/>
- 피드상세뷰 업데이트 시점 변경 변경했습니다.
- 댓글창 UI 이슈 수정했습니다. 
- 탈퇴한 유저에 대한 분기처리 반영했습니다. 
<br/>
- 코멘트 확인 부탁드립니다 ❗️
<br/>
- 피드 수정 후 수정된 데이터 즉시 반영
https://github.com/user-attachments/assets/43be9e34-0d65-419d-af66-73d91dab5b51
- 댓글창 내 커서 위치 수정
https://github.com/user-attachments/assets/e5bc4280-4bb5-4165-9453-df6dca76e6c7
- 탈퇴한 유저 UI 분기처리 반영
<br/>
<br/>
<br/>
> [Chore] #340 - 피드상세뷰 업데이트 시점 변경 및 댓글창 UI 이슈 수정

- WSSiOS/WSSiOS.xcodeproj/project.pbxproj
- WSSiOS/WSSiOS/Config.xcconfig
- WSSiOS/WSSiOS/Network/User/UserService.swift
- WSSiOS/WSSiOS/Resource/Constants/URLs/URLs.swift
- WSSiOS/WSSiOS/Source/Data/DTO/UserInfoResult.swift
- WSSiOS/WSSiOS/Source/Data/Repository/UserRepository.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewModel/MyPageViewModel.swift
> [Network] #345 - userId 연결

- WSSiOS/WSSiOS.xcodeproj/project.pbxproj
- WSSiOS/WSSiOS.xcodeproj/xcshareddata/xcschemes/WSSiOS.xcscheme
close #380
<br/>
개발용과 배포용을 구분하여 프로비저닝 세팅 완료하였습니다!
<br/>
> [Setting] #380 - 프로비저닝 파일 세팅

- WSSiOS/WSSiOS/Source/Presentation/Home/HomeNoticeDetail/HomeNoticeDetailView/HomeNoticeDetailAssistantView/HomeNoticeDetailContentView.swift
- close #389 
<br/>
- 공지사항 텍스트 내 하이퍼링크 기능을 구현했습니다. 
<br/>
`UITextView`의 프로퍼티인 [dataDetectorTypes](https://developer.apple.com/documentation/uikit/uitextview/datadetectortypes) = .link로 설정하면 자동으로 링크를 인식해서 하이퍼링크가 적용됩니다.
수정되지 않도록 `isEditable = false` 로 설정해두었습니다. 
```
noticeContentTextView.do {
$0.textColor = .wssBlack
$0.dataDetectorTypes = .link
$0.isEditable = false
}
```
<br/>
<br/>
간단하네요! 미리 찾아준 이나 최고임
<br/>
[[iOS] iOS에서 텍스트뷰의 텍스트 내 링크 하이퍼링크로 연결하기](https://borabong.tistory.com/18)
<br/>
> [Chore] #389 - 공지사항 텍스트 하이퍼링크 기능 구현 

- WSSiOS/WSSiOS/Resource/Extensions/UILabel+.swift
- close #393
<br/>
UILabel에서 이모지가 깨지는 문제를 해결했습니다. 
<br/>
**이모지의 종류에는 단일문자와 조합문자가 있습니다.**
**단일문자란?**
하나의 유니코드 코드포인트로 구성되어 있는 이모지
ex) ❤️ (U+2764), 😀 (U+1F600) -> 하나의 코드 유닛으로 계산
**조합문자란?**
여러개의 코드포인트를 조합한 이모지
ex) ❤️‍🔥 -> 3개의 코드 유닛으로 계산
•	U+2764 → ❤️
•	U+200D → 제로 너비 조인(ZWJ, Zero-Width Joiner)
•	U+1F525 → 🔥
UILabel의 kerning 적용 시 범위를 attributedString.length - 1로 설정했었습니다.
텍스트의 **마지막 문자가 조합문자일 경우, 범위가 조합문자의 일부 코드 유닛만 포함해 이모지가 깨지는 문제가 발생했습니다.**
범위 설정 시 attributedString.length를 그대로 사용하여 해결했습니다. 
<br/>
<br/>
싱기방기
<br/>
<br/>
> [Fix] #393 - UILabel 이모지 깨지는 문제 해결

- WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeViewModel/HomeViewModel.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewController/MyPageViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewModel/MyPageViewModel.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingViewModel/MyPageDeleteIDViewModel.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingViewModel/MyPageInfoViewModel.swift
- close #441 
<br/>
로그아웃을 하고 다른 소셜로그인으로 재로그인하였을 때 전 데이터가 남아있는 에러를 수정하였습니다.
<br/>
MyPageViewModel 의 init 에서 profileId 를 호출하기 때문에 HomeVM 에서 서버연결을 통해 UserId 를 UserDefault 에 새로 저장된 값이 proflieId 에 저장되지 않는 이슈가 발생했습니다.
(TabBar 에서 MyPage VM 을 먼저 세팅하고 나중에 Home ViewDidLoadEvent 호출하기 때문)
따라서 profileId 가 0일때 새로운 값을 가져올 수 있도록 처리하였습니다.
<br/>
```swift
//In MyPageViewModel
//viewWillAppear 를 reload 하는 Subject 호출
private let reloadSubject = PublishSubject<Void>()
Observable.merge(input.viewWillAppearEvent, reloadSubject)
~~ 작업 ~~
.flatMapLatest { [weak self]  _ -> Observable<Void> in
~~작업~~
//만약 profileId 가 0이라면 UserDefault 에 저장된 값이 없다는 뜻
//따라서 새로 저장된 값을 다시 부르고, viewWIllAppear 를 다시 호출
if self.profileId == 0 {
self.profileId =  UserDefaults.standard.integer(forKey: StringLiterals.UserDefault.userId) …
```
> [Fix] #441 - 로그아웃시 데이터 남아있는 에러 수정

- WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileView/MyPageFeedView.swift
> [Fix] #457 - MyPageFeedView 오탈자 수정

- WSSiOS/WSSiOS.xcodeproj/project.pbxproj
- WSSiOS/WSSiOS.xcodeproj/xcshareddata/xcschemes/WSSiOS.xcscheme
- close #463 
<br/>
Debug 용 App ID 를 새로 팠습니다!
<br/>
bundle ID 가  `kr.websoso.debug` 로 변경되었습니다.
새로운 프로비저닝 파일은 Secure 레포에 올려놓았습니다.
내일 모레 있을 QA 는 Debug 테플로 진행할 예정입니다.
<br/>
> [Setting] #463 - Debug 버전 앱 세팅

- WSSiOS/WSSiOS/Network/Notification/NotificationService.swift
- WSSiOS/WSSiOS/Resource/Constants/URLs/URLs.swift
- WSSiOS/WSSiOS/Source/Data/DTO/NoticeResult.swift
- WSSiOS/WSSiOS/Source/Data/Repository/NotificationRepository.swift
- WSSiOS/WSSiOS/Source/Presentation/Base/WSSTabBarItem.swift
- WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeView/HomeAssistantView/HomeHeaderView.swift
- WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeViewController/HomeViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeViewModel/HomeViewModel.swift
- close #445 
<br/>
- 비열람 알림 존재 여부 조회 API 연결 구현 했습니다. 
<br/>
- 기존 API 연결 코드와 동일합니다. 
- DTO 내에 Boolean 변수 하나밖에 없어서 Entity는 따로 만들지 않았습니다. 
<br/>
<br/>
<br/>
<br/>
> [Feat] #445 - 비열람 알림 존재 여부 조회 API 연결 구현 

- WSSiOS/WSSiOS/Resource/Helper/NotificationHelper.swift
- close #
<br/>
<br/>
<br/>
```swift
abc
```
<br/>
<br/>
<br/>
<br/>
> [Fix] #434 - 변수명 수정 적용

- WSSiOS/WSSiOS/Source/Presentation/Home/HomeNotice/HomeNoticeViewController/HomeNoticeViewController.swift
- close #469 
<br/>
- 공지사항 내 화면 전환 시 메인 스레드에서 동작하도록 수정했습니다. 
<br/>
<br/>
- 크래쉬 안나고 잘 작동합니다~
<br/>
<br/>
<br/>
> [Fix] #469 - 공지사항 내 화면 전환 시 메인 스레드에서 동작하도록 수정

- WSSiOS/WSSiOS.xcodeproj/project.pbxproj
- WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
- WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailView.swift
- WSSiOS/WSSiOS/Source/Presentation/Home/HomeNotification/HomeNotificationView/HomeNotificationView.swift
- WSSiOS/WSSiOS/Source/Presentation/Library/LibraryView/LibraryChildView.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileView/MyPageFeedDetailView.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileView/MyPageFeedView.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewController/MyPageFeedDetailViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewController/MyPageViewController.swift
- WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailView.swift
- WSSiOS/WSSiOS/Source/Presentation/Search/DetailSearch/DetailSearchView/DetailSearchAssistantView/DetailSearchResultNovelView.swift
- WSSiOS/WSSiOS/Source/Presentation/Search/DetailSearch/DetailSearchView/DetailSearchResultView.swift
- WSSiOS/WSSiOS/Source/Presentation/Search/NormalSearch/NormalSearchView/NormalAssistantView/NormalSearchResultView.swift
- close #480 
<br/>
- UX 개선을 위한 ScrollIndicator 설정했습니다. 
<br/>
X
<br/>
| 공지사항 리스트 | 작품 정보 | 일반탐색 결과 |
| -- | -- | -- |
| ![Simulator Screen Recording - iPhone 13 mini - 2025-02-19 at 00 21 48](https://github.com/user-attachments/assets/ea6e3be7-f775-4d96-b5b7-ec1c1079a1fc)| ![Simulator Screen Recording - iPhone 13 mini - 2025-02-19 at 00 19 22](https://github.com/user-attachments/assets/f879aa1c-285d-4118-aa9a-d5d40b443092)|![Simulator Screen Recording - iPhone 13 mini - 2025-02-19 at 00 19 40](https://github.com/user-attachments/assets/d8f0c3b3-68b0-4390-95eb-20629301698d)|
| 상세탐색 결과 | 피드 상세 | 마이페이지 보관함 | 마이페이지 내 활동 |
| -- | -- | -- | -- |
|![Simulator Screen Recording - iPhone 13 mini - 2025-02-19 at 00 22 59](https://github.com/user-attachments/assets/0325aee0-7caf-4843-8422-15328e37492 …
> [Chore] #480 - 사용자 경험 개선을 위한 ScrollIndicator 설정

- WSSiOS/WSSiOS.xcodeproj/project.pbxproj
- WSSiOS/WSSiOS.xcodeproj/xcshareddata/xcschemes/WSSiOS.xcscheme
> [Release] 1.1.0 업데이트 준비
